# ~/.aerospace.toml

after-startup-command = [
  'exec-and-forget borders active_color=0xffE6C384 inactive_color=0xff2A2A37 width=6.0'
]

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

exec-on-workspace-change = [
  '/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE'
]

on-focus-changed = [
  'move-mouse window-lazy-center',
  'exec-and-forget sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)'
]

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

on-mode-changed = [
  'exec-and-forget sketchybar --trigger aerospace_mode_change MODE=$(aerospace list-modes --current)'
]

[[on-window-detected]]
if.app-id = 'company.thebrowser.dia'
run = 'layout floating tiling'

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 4
outer.right = 4
outer.top = 38
outer.bottom = 4

[mode.main.binding]
ctrl-shift-alt-cmd-h = 'focus left'
ctrl-shift-alt-cmd-j = 'focus down'
ctrl-shift-alt-cmd-k = 'focus up'
ctrl-shift-alt-cmd-l = 'focus right'

ctrl-shift-alt-cmd-1 = 'workspace 1'
ctrl-shift-alt-cmd-2 = 'workspace 2'
ctrl-shift-alt-cmd-3 = 'workspace 3'
ctrl-shift-alt-cmd-4 = 'workspace 4'
ctrl-shift-alt-cmd-5 = 'workspace 5'
ctrl-shift-alt-cmd-6 = 'workspace 6'
ctrl-shift-alt-cmd-7 = 'workspace 7'
ctrl-shift-alt-cmd-8 = 'workspace 8'
ctrl-shift-alt-cmd-9 = 'workspace 9'

ctrl-shift-alt-cmd-m = 'mode move'

ctrl-shift-alt-cmd-f = 'fullscreen'
ctrl-shift-alt-cmd-t = 'layout tiles horizontal vertical'
ctrl-shift-alt-cmd-s = 'layout accordion horizontal vertical'
ctrl-shift-alt-cmd-e = 'layout floating tiling'
ctrl-shift-alt-cmd-minus = 'resize smart -50'
ctrl-shift-alt-cmd-equal = 'resize smart +50'
ctrl-shift-alt-cmd-r = 'reload-config'

# Focus monitor by direction
ctrl-shift-alt-cmd-right = 'focus-monitor next'
ctrl-shift-alt-cmd-left = 'focus-monitor prev'

[mode.move.binding]
h = 'move left'
j = 'move down'
k = 'move up'
l = 'move right'
1 = ['move-node-to-workspace 1', 'workspace 1']
2 = ['move-node-to-workspace 2', 'workspace 2']
3 = ['move-node-to-workspace 3', 'workspace 3']
4 = ['move-node-to-workspace 4', 'workspace 4']
5 = ['move-node-to-workspace 5', 'workspace 5']
6 = ['move-node-to-workspace 6', 'workspace 6']
7 = ['move-node-to-workspace 7', 'workspace 7']
8 = ['move-node-to-workspace 8', 'workspace 8']
9 = ['move-node-to-workspace 9', 'workspace 9']
esc = 'mode main'
enter = 'mode main'
